Repository nozomi-terasawa/ShareFit, pull requests merged in 2024-11, with the labels that each got.

#44 ヘッダーの修正
  app/src/main/java/com/example/fitbattleandroid/ui/common/Header.kt
Labels: ui

#45 buttomのスペルミス修正
  app/src/main/java/com/example/fitbattleandroid/ui/common/Buttom.kt
Labels: ui

#46 GeofenceのAPIの実装の途中
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/fitbattleandroid/activity/PermissionsRationaleActivity.kt
  app/src/main/java/com/example/fitbattleandroid/data/EncounterRemoteDatasource.kt
  app/src/main/java/com/example/fitbattleandroid/repository/GeofenceEntryRepository.kt
  app/src/main/java/com/example/fitbattleandroid/repositoryImpl/GeofenceEntryRepositoryImpl.kt
  app/src/main/java/com/example/fitbattleandroid/ui/navigation/NavHost.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/LoginScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/MapScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/RegistrationScreen.kt
  app/src/main/java/com/example/fitbattleandroid/viewmodel/AuthViewModel.kt
  app/src/main/java/com/example/fitbattleandroid/viewmodel/GeofenceMapViewModel.kt
Labels: API

#52 Hiltの導入とジオフェンス取得APIの実装
  .idea/deploymentTargetSelector.xml
  .idea/inspectionProfiles/Project_Default.xml
  app/build.gradle.kts
  app/src/main/java/com/example/fitbattleandroid/FitBattleApplication.kt
  app/src/main/java/com/example/fitbattleandroid/MainActivity.kt
  app/src/main/java/com/example/fitbattleandroid/data/FitnessRemoteDataSource.kt
  app/src/main/java/com/example/fitbattleandroid/data/remote/FetchGeoFenceRes.kt
  app/src/main/java/com/example/fitbattleandroid/data/remote/GeoFenceInfoRes.kt
  app/src/main/java/com/example/fitbattleandroid/di/DiModule.kt
  app/src/main/java/com/example/fitbattleandroid/repository/FetchGeoFenceInfoRepository.kt
  app/src/main/java/com/example/fitbattleandroid/repositoryImpl/FetchGeoFenceInfoRepositoryImpl.kt
  app/src/main/java/com/example/fitbattleandroid/repositoryImpl/WebSocketRepositoryImpl.kt
  app/src/main/java/com/example/fitbattleandroid/viewmodel/MapViewModel.kt
  build.gradle.kts
Labels: geofence, API
