Repository nozomi-terasawa/ShareFit, pull requests merged in 2024-10, with the labels that each got.

#2 [UI] LoginScreen作成
  app/build.gradle.kts
  app/src/main/java/com/example/fitbattleandroid/ui/common/TextFeild.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/LoginScreen.kt
  gradle/libs.versions.toml
Labels: ui

#3 ジオフェンス通知の作成
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/fitbattleandroid/notification/NotificationChannels.kt
  app/src/main/java/com/example/fitbattleandroid/notification/Notifications.kt
  app/src/main/java/com/example/fitbattleandroid/ui/common/Dialog.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/MapScreen.kt
  app/src/main/res/drawable/baseline_swap_horizontal_circle_24.xml
Labels: geofence

#4 [UI]TopScreenの作成
  app/src/main/java/com/example/fitbattleandroid/ui/screen/TopScreen.kt
Labels: ui

#5 GrayZoneのComposableの作成
  app/src/main/java/com/example/fitbattleandroid/ui/common/GrayZone.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/LoginScreen.kt
Labels: ui

#6 ジオフェンス処理用のViewModelを作成
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/fitbattleandroid/receiver/GeofenceBroadcastReceiver.kt
  app/src/main/java/com/example/fitbattleandroid/viewmodel/LocationViewModel.kt
  gradle/libs.versions.toml
Labels: geofence

#7 LocationViewModelをGeofenceViewModelに変更
  app/src/main/java/com/example/fitbattleandroid/viewmodel/GeofenceViewModel.kt
  app/src/main/java/com/example/fitbattleandroid/viewmodel/LocationViewModel.kt
Labels: geofence

#8 ジオフェンスの実装ロジックをmainにマージ
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/fitbattleandroid/notification/NotificationChannels.kt
  app/src/main/java/com/example/fitbattleandroid/notification/Notifications.kt
  app/src/main/java/com/example/fitbattleandroid/receiver/GeofenceBroadcastReceiver.kt
  app/src/main/java/com/example/fitbattleandroid/ui/common/Dialog.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/MapScreen.kt
  app/src/main/java/com/example/fitbattleandroid/viewmodel/GeofenceViewModel.kt
  app/src/main/java/com/example/fitbattleandroid/viewmodel/LocationViewModel.kt
  app/src/main/res/drawable/baseline_swap_horizontal_circle_24.xml
  gradle/libs.versions.toml
Labels: geofence

#9 走る人のアニメーション追加
  app/src/main/java/com/example/fitbattleandroid/ui/animetion/HumanRun.kt
  app/src/main/res/drawable-nodpi/pngtreerunning_character_silhouette_png_free_4627520.png
  app/src/main/res/drawable-nodpi/pngtreesmoke_white_dream_fog_6860988.png
Labels: ui, animetion

#10 registration screen作成
  app/src/main/java/com/example/fitbattleandroid/ui/screen/RegistrationScreen.kt
Labels: ui

#11 BottomNavigationの作成
  app/build.gradle.kts
  app/src/main/java/com/example/fitbattleandroid/MainActivity.kt
  app/src/main/java/com/example/fitbattleandroid/ui/navigation/NavHost.kt
  gradle/libs.versions.toml
Labels: ui

#14 Navigationの重複をなくした
  app/src/main/java/com/example/fitbattleandroid/ui/screen/LoginScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/RegistrationScreen.kt
Labels: ui

#15 NavHostとMainActivityの追加
  app/src/main/java/com/example/fitbattleandroid/MainActivity.kt
  app/src/main/java/com/example/fitbattleandroid/ui/navigation/NavHost.kt
Labels: ui

#19 FireAnimetionの追加
  app/src/main/java/com/example/fitbattleandroid/ui/animetion/Fire.kt
  app/src/main/res/drawable-nodpi/pngtreeburning_fire_5637806.png
Labels: ui, animetion

#20 消費カロリー画面の作成
  app/src/main/java/com/example/fitbattleandroid/ui/animetion/Fire.kt
  app/src/main/java/com/example/fitbattleandroid/ui/common/CountdownTo24.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/FitnessMemoryScreen.kt
  app/src/main/res/drawable/fire.jpg
Labels: ui

#21 Develop UIのマージ
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/fitbattleandroid/FitBattleApplication.kt
  app/src/main/java/com/example/fitbattleandroid/MainActivity.kt
  app/src/main/java/com/example/fitbattleandroid/ui/animetion/Fire.kt
  app/src/main/java/com/example/fitbattleandroid/ui/animetion/HumanRun.kt
  app/src/main/java/com/example/fitbattleandroid/ui/common/CountdownTo24.kt
  app/src/main/java/com/example/fitbattleandroid/ui/common/GrayZone.kt
  app/src/main/java/com/example/fitbattleandroid/ui/common/TextFeild.kt
  app/src/main/java/com/example/fitbattleandroid/ui/navigation/NavHost.kt
  app/src/main/java/com/example/fitbattleandroid/ui/permissioncheck/LocationPermissionCheck.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/FitnessMemoryScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/LoginScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/MapScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/RegistrationScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/SampleScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/TopScreen.kt
  app/src/main/res/drawable-nodpi/pngtreeburning_fire_5637806.png
  app/src/main/res/drawable-nodpi/pngtreerunning_character_silhouette_png_free_4627520.png
  app/src/main/res/drawable-nodpi/pngtreesmoke_white_dream_fog_6860988.png
  app/src/main/res/drawable/fire.jpg
  build.gradle.kts
  gradle/libs.versions.toml
Labels: ui

#23 アイコンとタイトルの変更
  app/build.gradle.kts
  app/src/main/java/com/example/fitbattleandroid/ui/screen/TopScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/theme/Color.kt
  app/src/main/java/com/example/fitbattleandroid/ui/theme/Theme.kt
  app/src/main/res/drawable-nodpi/sharefit_jpeg.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  gradle/libs.versions.toml
Labels: ui

#24 総カロリーの取得
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/fitbattleandroid/MainActivity.kt
  app/src/main/java/com/example/fitbattleandroid/ui/navigation/NavHost.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/EncounterHistoryScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/FitnessMemoryScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/MapScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/SampleScreen.kt
  app/src/main/java/com/example/fitbattleandroid/viewmodel/HealthConnectViewModel.kt
Labels: health

#25 ボタン操作と別でCompose時に一度だけカロリーを取得するように修正
  app/src/main/java/com/example/fitbattleandroid/ui/screen/FitnessMemoryScreen.kt
  app/src/main/java/com/example/fitbattleandroid/viewmodel/HealthConnectViewModel.kt
Labels: health

#27 アプリアイコン変更
  .idea/.name
  .idea/compiler.xml
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  .idea/vcs.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/mainfire.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
Labels: ui

#28 ・アプリアイコン変更
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
Labels: ui

#31 APIを追加する
  app/build.gradle.kts
  app/src/main/java/com/example/fitbattleandroid/data/NewPassingInfo.kt
  app/src/main/java/com/example/fitbattleandroid/receiver/GeofenceBroadcastReceiver.kt
  app/src/main/java/com/example/fitbattleandroid/repository/WebSocketRepository.kt
  app/src/main/java/com/example/fitbattleandroid/repositoryImpl/WebSocketRepositoryImpl.kt
  app/src/main/java/com/example/fitbattleandroid/viewmodel/GeofenceViewModel.kt
  gradle/libs.versions.toml
Labels: API

#26 develop/health-connectをdevelop-mainへマージ
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/fitbattleandroid/MainActivity.kt
  app/src/main/java/com/example/fitbattleandroid/ui/navigation/NavHost.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/FitnessMemoryScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/SampleScreen.kt
  app/src/main/java/com/example/fitbattleandroid/viewmodel/HealthConnectViewModel.kt
Labels: health

#33 色設定
  app/src/main/java/com/example/fitbattleandroid/ui/common/CountdownTo24.kt
  app/src/main/java/com/example/fitbattleandroid/ui/common/TextFeild.kt
  app/src/main/java/com/example/fitbattleandroid/ui/navigation/NavHost.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/EncounterHistoryScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/FitnessMemoryScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/LoginScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/MapScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/RegistrationScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/TopScreen.kt
  app/src/main/java/com/example/fitbattleandroid/viewmodel/HealthConnectViewModel.kt
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
Labels: ui

#34 ・デザイン
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/fitbattleandroid/ui/screen/FitnessMemoryScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/MapScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/TopScreen.kt
Labels: ui

#35 ・炎のアニメーション作成
  app/src/main/java/com/example/fitbattleandroid/ui/animetion/Fire.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/FitnessMemoryScreen.kt
Labels: ui

#36 タイトルの画像を短く
  app/src/main/java/com/example/fitbattleandroid/ui/animetion/Fire.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/TopScreen.kt
  app/src/main/res/drawable-nodpi/title.png
Labels: ui

#38 CommonComposableの作成
  app/src/main/java/com/example/fitbattleandroid/ui/common/Background.kt
  app/src/main/java/com/example/fitbattleandroid/ui/common/Bottom.kt
  app/src/main/java/com/example/fitbattleandroid/ui/common/Header.kt
  app/src/main/java/com/example/fitbattleandroid/ui/common/Text.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/LoginScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/RegistrationScreen.kt
  app/src/main/java/com/example/fitbattleandroid/ui/screen/TopScreen.kt
Labels: ui
